name: Test API

on: push

jobs:
    build:
        name: Test API
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '11'
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-
            - run: |
                  java -version
                  echo $JAVA_HOME
            - run: |
                  ls
                  mvn test -f ./blog-api/pom.xml
